
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'marketing_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  +copy_grants: true
  +sql_header: "alter session set timezone = 'UTC';"
  +persist_docs:
    relation: true
    columns: true
  marketing_project:
    2_bronze:
      +materialized: table
      +tags: bronze
      +docs:
        node_color: "#CD7F32"
      meta:
        +tags: meta
        +description: "ad data from meta"
        +schema: bronze_meta
      tiktok:
        +tags: tiktok
        +description: "ad data from tiktok"
        +schema: bronze_tiktok
      google:
        +tags: google
        +description: "ad data from google"
        +schema: bronze_google     
      calendar:
        +schema: bronze_calendar

    3_silver:
      +materialized: table
      +tags: silver
      +docs:
        node_color: "#8A8A8A"
      tiktok:
        +schema: silver_tiktok
      meta:
        +schema: silver_meta
      google:
        +schema: silver_google

    4_gold:
      +materialized: table
      +tags: gold
      +docs:
        node_color: "#FFD700"
      marketing:
        +schema: gold_marketing
